### ISSUE TITLE
How does this work/Does it work with newsletters that want you to confirm your subscription?

### ISSUE THREAD

**Issue by finn-matti** [leafac/kill-the-newsletter.com#23]
Very nice idea @leafac !

I was wondering how this handles newsletters that want you to confirm your subscription. I assume also for those there will be a feed entry created that should include a confirmation link?

**Comment by jtagcat** [comment]
There will be a feed entry with the confirmation link.

In theory, https://github.com/JoeBiellik/pleasenospam could be used with KTN to have a web mailbox, but I think that's not needed.

**Comment by finn-matti** [comment]
Alright. Thanks for the explanation.

**Comment by leafac** [comment]
Thanks for the kind words.

Did you get it to work with the newsletter that required confirmation?

I agree in thinking that **please, no spam** isn’t needed in conjunction with **Kill the Newsletter!**

**Comment by finn-matti** [comment]
>Did you get it to work with the newsletter that required confirmation?

I am not sure anymore that https://www.localoptimist.com/ even has confirmation. Maybe they block the domain? I have yet to receive an issue of their newsletter.

**Comment by leafac** [comment]
@finn-matti: I tried signing up both with a **Kill the Newsletter!** email and a regular email. I didn’t receive emails in either. I don’t think it’s an issue with **Kill the Newsletter!**; maybe they just don’t send a confirmation email when you sign up.

**Comment by JiangWeixian** [comment]
I use it to subscribe https://console.dev/ , and paste the xml url into NetNewsWire. However it alert me `feed not found`. The reason maybe related to I didn't confirm the email?
