### ISSUE TITLE
Feature request: Add buttons to copy the email address and feed urls to the clipboard

### ISSUE THREAD

**Issue by soheilpro** [leafac/kill-the-newsletter.com#27]
Hi. Thank you for the amazing product and service.

Is it possible to have buttons that copy the created inbox's email address and feed URL to the clipboard?

Should be very easy with https://clipboardjs.com

**Comment by leafac** [comment]
There you go: https://github.com/leafac/kill-the-newsletter.com/commit/cb0bf74025cf9b182bdacebfb5c6099e7c77b0c9

**Comment by soheilpro** [comment]
Awesome! Thank you.
