### ISSUE TITLE
Duplicate Posts

### ISSUE THREAD

**Issue by InsaneSplash** [leafac/kill-the-newsletter.com#31]
Great tool!!

I am picking up some issues around duplicate posts being created. I suspect it may have to do with the email having a CC or a second email address. Is there anything that can be done to only create 1 post from an email regardless of who it's destined for etc?

**Comment by jtagcat** [comment]
Having both the to and cc, it's the intended behaviour; feed readers often can deduplicate feed entries. It may be conceivable to define a special case / workaround on ktn's side, though.

Could you check whether the e-mails are identical identical. For newsletters, I'd suggest comparing the link targets. Are they different? You might have 2 subscriptions at a time gong.

Without providing the service in question, and no further information, it's hard to help / check if a bugfix works.

**Comment by InsaneSplash** [comment]
The posts are duplicates and are 100% the same.

Here is our public reader: https://rss.rocketnet.co.za

**Comment by leafac** [comment]
Now **Kill the Newsletter!** doesn’t add repeated entries for a single email whose `to`, `cc`, `bcc`, and so forward, all point to the same address. I think that’s all we can do on our side.

Enjoy.
