### ISSUE TITLE
Hardcoded form action URI breaks reverse proxy if under a subdirectory

### ISSUE THREAD

**Issue by kloon15** [leafac/kill-the-newsletter.com#34]
The error is on index.ts:208 line `<form method="POST" action="/">`
I dont know what the best approach is, but i replaced `/` with `#` and that fixed the problem.

**Comment by Pinjasaur** [comment]
My instinct would be either `action="./"` or just omit the `action` attribute all together which would just POST to the _current_ URL.

Link to source line: https://github.com/leafac/kill-the-newsletter.com/blob/master/index.ts#L208

**Comment by leafac** [comment]
Thanks for reporting the issue.
