### ISSUE TITLE
Can't deploy to DigitalOcean App platform

### ISSUE THREAD

**Issue by jgannondo** [leafac/kill-the-newsletter.com#37]
Hi team - I'm a DigitalOcean employee trying to deploy this app via the DigitalOcean App Platform.

The app seems to build and load, but when I visit the app URL (https://kill-the-newsletter-com-42ke7.ondigitalocean.app/) I get this error:

> upstream connect error or disconnect/reset before headers. reset reason: connection termination

Any idea what I may need to do or change to get around this? Thanks much!

**Comment by leafac** [comment]
Not right off the bat, but we can figure it out together. It seems like the application itself is running fine; it’s some intermediary that’s causing issues. So we’ll move them out of the way for a moment to figure out what’s going on.

From **Kill the Newsletter!**’s side there’s only one intermediary: Caddy (it’s there to handle TLS/HTTPS). We can move it out of the way for a moment by allowing port 8000 (or whatever other port [you configured](https://github.com/leafac/kill-the-newsletter.com/blob/ff1101adb734a2c7c7bd5e2718e2c460e8d2c05e/package.json#L53)) on the [firewall](https://github.com/leafac/kill-the-newsletter.com/tree/ff1101adb734a2c7c7bd5e2718e2c460e8d2c05e#deploy-your-own-instance-self-host). Then try to visit `http://kill-the-newsletter-com-42ke7.ondigitalocean.app:8000` (note the `http` and the `:8000`).

If that doesn’t work, then there may be more intermediaries in the infrastructure you’re using. Judging by the HTTP headers you’re using Cloudflare. You may try to turn that off and see how it goes.

Let me know if you got it work. Good luck.

**Comment by leafac** [comment]
Any news?

**Comment by leafac** [comment]
We’ll close this for now. If you still need help, let me know.
